version: '3.8'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - dbdata:/data/db
    env_file:
      - .env.mongodb

  app:
    build: .
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  dbdata:
